replicaCount: 1

image:
  repository: feedfarmer
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: feedfarmer.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

env:
  port: "8080"
  dbPath: /data/feedfarmer.db

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClassName: ""
  mountPath: /data
